### ISSUE TITLE
i can't fin houndmaster terror radius on the files

### ISSUE THREAD

**Issue by SamLore** [Masusder/DBDSounds#3]
did you uploaded them? if not, will you plan on future?
in fact, i really dislike to bother other people like this, i'm sorry, so i ask what exactly you do to extract terror radius? 
all i see is people telling to use uviewer or fmodel, and as much i can take audio files from them, none of them can play terror radius/can't find the terror radius files at all.

**Comment by SamLore** [comment]
close this issue, i am very stupid actually
![image](https://github.com/user-attachments/assets/ca94dc2e-ccc1-4085-8f17-7bed25a17857)
in case anyone have the same niche issue, use fmodel and search for bnk files, then use foobar to take the audios
![image](https://github.com/user-attachments/assets/3a4d3f21-655f-4f64-9595-ab4db694239d)
they gonna be scrambled, but very easy to indentify them all by the duration and size..

**Comment by Masusder** [comment]
Terror radius is there (link below), but since I'm only simulating how WWISE works it's struggling to mix it correctly due to the fact how terror radius works. I use my own tool for audio extraction, [source code is here](https://github.com/Masusder/UEParser/blob/master/UEParser/Source/Parser/Wwise/WwiseFileHandler.cs).

https://github.com/Masusder/DBDSounds/blob/main/Converted%20Files/AudioEvents/CHARACTER/SURVIVOR/SVR_COMMON/SVR_GAMESTART/AudioEvent_Survivor_GameStart_Proximity%20(AudioStateKillers%3D2627811056)%20%5BAudioSwitchProximity%3Dplay%5D%5BAudioSwitchStatesSurvivor%3DDying%5D%20%7Bs%7D.ogg
